apiVersion: apps/v1
kind: Deployment
metadata:
  name: devmainapp
  labels:
    app: devmainapp
    kubernetes.azure.com/generator: devhub
  namespace: devmainapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devmainapp
  template:
    metadata:
      labels:
        app: devmainapp
    spec:
      containers:
        - name: devmainapp
          image: devmainapp.azurecr.io/devmainapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-url
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
