apiVersion: v1
kind: Service
metadata:
  name: devmainapp
  namespace: devmainapp
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: devmainapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
